# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ryan/AppData/Local/Temp/fit_params_windowFMKaxF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(668, 741)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.number_terms_spinner = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_terms_spinner.sizePolicy().hasHeightForWidth())
        self.number_terms_spinner.setSizePolicy(sizePolicy)
        self.number_terms_spinner.setProperty("value", 1)
        self.number_terms_spinner.setObjectName("number_terms_spinner")
        self.gridLayout.addWidget(self.number_terms_spinner, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.fit_function_combobox = QtWidgets.QComboBox(Form)
        self.fit_function_combobox.setObjectName("fit_function_combobox")
        self.fit_function_combobox.addItem("")
        self.fit_function_combobox.addItem("")
        self.fit_function_combobox.addItem("")
        self.gridLayout.addWidget(self.fit_function_combobox, 1, 0, 1, 1)
        self.apply_btn = QtWidgets.QPushButton(Form)
        self.apply_btn.setObjectName("apply_btn")
        self.gridLayout.addWidget(self.apply_btn, 3, 1, 1, 1)
        self.offset_checkbox = QtWidgets.QCheckBox(Form)
        self.offset_checkbox.setObjectName("offset_checkbox")
        self.gridLayout.addWidget(self.offset_checkbox, 2, 0, 1, 1)
        self.done_btn = QtWidgets.QPushButton(Form)
        self.done_btn.setObjectName("done_btn")
        self.gridLayout.addWidget(self.done_btn, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.parameters_table = QtWidgets.QTableWidget(Form)
        self.parameters_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameters_table.setMidLineWidth(1)
        self.parameters_table.setAlternatingRowColors(True)
        self.parameters_table.setObjectName("parameters_table")
        self.parameters_table.setColumnCount(5)
        self.parameters_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.parameters_table, 4, 0, 1, 3)
        self.fit_method_combobox = QtWidgets.QComboBox(Form)
        self.fit_method_combobox.setObjectName("fit_method_combobox")
        self.fit_method_combobox.addItem("")
        self.fit_method_combobox.addItem("")
        self.gridLayout.addWidget(self.fit_method_combobox, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.fit_function_combobox.currentIndexChanged['QString'].connect(Form.fit_model_selected)
        self.number_terms_spinner.valueChanged['int'].connect(Form.number_terms_changed)
        self.apply_btn.clicked.connect(Form.apply_btn_clicked)
        self.done_btn.clicked.connect(Form.done_btn_clicked)
        self.offset_checkbox.toggled['bool'].connect(Form.offset_cb_toggled)
        self.fit_method_combobox.activated['QString'].connect(Form.fit_method_selected)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "Number of Terms:"))
        self.fit_function_combobox.setItemText(0, _translate("Form", "Exponential"))
        self.fit_function_combobox.setItemText(1, _translate("Form", "Gaussian Modified Exponential"))
        self.fit_function_combobox.setItemText(2, _translate("Form", "Custom Equation"))
        self.apply_btn.setText(_translate("Form", "Apply"))
        self.offset_checkbox.setText(_translate("Form", "Include Constant Offset"))
        self.done_btn.setText(_translate("Form", "Done"))
        item = self.parameters_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Parameter"))
        item = self.parameters_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Guess"))
        item = self.parameters_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Lower Bound"))
        item = self.parameters_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Upper Bound"))
        item = self.parameters_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Result"))
        self.fit_method_combobox.setItemText(0, _translate("Form", "Pseudolinear (recommended)"))
        self.fit_method_combobox.setItemText(1, _translate("Form", "Fully Nonlinear Least Squares"))
