# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ryan/AppData/Local/Temp/moco_control_guiOQhuAw.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 475)
        MainWindow.setMinimumSize(QtCore.QSize(630, 475))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_container = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_container.sizePolicy().hasHeightForWidth())
        self.tab_container.setSizePolicy(sizePolicy)
        self.tab_container.setMaximumSize(QtCore.QSize(600, 400))
        self.tab_container.setObjectName("tab_container")
        self.set_mono_tab = QtWidgets.QWidget()
        self.set_mono_tab.setObjectName("set_mono_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.set_mono_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -1, 591, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.set_mono_group_1 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.set_mono_group_1.setTitle("")
        self.set_mono_group_1.setObjectName("set_mono_group_1")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.set_mono_group_1)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 30, 202, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.com_port_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.com_port_layout.setContentsMargins(0, 0, 0, 0)
        self.com_port_layout.setObjectName("com_port_layout")
        self.com_port_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.com_port_label.setWordWrap(True)
        self.com_port_label.setObjectName("com_port_label")
        self.com_port_layout.addWidget(self.com_port_label)
        self.visa_resource_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.visa_resource_combobox.setMinimumSize(QtCore.QSize(200, 0))
        self.visa_resource_combobox.setObjectName("visa_resource_combobox")
        self.com_port_layout.addWidget(self.visa_resource_combobox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.set_mono_group_1)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(350, 20, 96, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.gr_density_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.gr_density_layout.setContentsMargins(0, 0, 0, 0)
        self.gr_density_layout.setObjectName("gr_density_layout")
        self.groove_density_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.groove_density_label.setWordWrap(True)
        self.groove_density_label.setObjectName("groove_density_label")
        self.gr_density_layout.addWidget(self.groove_density_label, 0, QtCore.Qt.AlignBottom)
        self.groove_density_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.groove_density_combobox.setObjectName("groove_density_combobox")
        self.groove_density_combobox.addItem("")
        self.groove_density_combobox.addItem("")
        self.groove_density_combobox.addItem("")
        self.groove_density_combobox.addItem("")
        self.groove_density_combobox.addItem("")
        self.groove_density_combobox.addItem("")
        self.gr_density_layout.addWidget(self.groove_density_combobox, 0, QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.set_mono_group_1, 1, 1, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem3, 8, 1, 1, 1)
        self.mono_initialize_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mono_initialize_button.setObjectName("mono_initialize_button")
        self.gridLayout.addWidget(self.mono_initialize_button, 8, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem5, 6, 1, 1, 1)
        self.set_mono_group_2 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.set_mono_group_2.setTitle("")
        self.set_mono_group_2.setObjectName("set_mono_group_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.set_mono_group_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 0, 151, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.backlash_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.backlash_label.setMinimumSize(QtCore.QSize(145, 0))
        self.backlash_label.setWordWrap(True)
        self.backlash_label.setObjectName("backlash_label")
        self.verticalLayout.addWidget(self.backlash_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.backlash_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.backlash_checkbox.setObjectName("backlash_checkbox")
        self.verticalLayout.addWidget(self.backlash_checkbox, 0, QtCore.Qt.AlignHCenter)
        self.backlash_layout = QtWidgets.QHBoxLayout()
        self.backlash_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.backlash_layout.setObjectName("backlash_layout")
        self.backlash_amount_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.backlash_amount_label.setObjectName("backlash_amount_label")
        self.backlash_layout.addWidget(self.backlash_amount_label, 0, QtCore.Qt.AlignLeft)
        self.backlash_amount_spinner = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.backlash_amount_spinner.setDecimals(1)
        self.backlash_amount_spinner.setMaximum(100.0)
        self.backlash_amount_spinner.setSingleStep(1.0)
        self.backlash_amount_spinner.setProperty("value", 10.0)
        self.backlash_amount_spinner.setObjectName("backlash_amount_spinner")
        self.backlash_layout.addWidget(self.backlash_amount_spinner)
        self.verticalLayout.addLayout(self.backlash_layout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.set_mono_group_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 0, 202, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.calib_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.calib_layout.setContentsMargins(0, 0, 0, 0)
        self.calib_layout.setObjectName("calib_layout")
        self.calib_wl_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_wl_label.sizePolicy().hasHeightForWidth())
        self.calib_wl_label.setSizePolicy(sizePolicy)
        self.calib_wl_label.setMinimumSize(QtCore.QSize(165, 0))
        self.calib_wl_label.setWordWrap(True)
        self.calib_wl_label.setObjectName("calib_wl_label")
        self.calib_layout.addWidget(self.calib_wl_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.calib_wl_spinner = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_wl_spinner.sizePolicy().hasHeightForWidth())
        self.calib_wl_spinner.setSizePolicy(sizePolicy)
        self.calib_wl_spinner.setMaximumSize(QtCore.QSize(95, 16777215))
        self.calib_wl_spinner.setDecimals(2)
        self.calib_wl_spinner.setMaximum(3000.0)
        self.calib_wl_spinner.setProperty("value", 230.0)
        self.calib_wl_spinner.setObjectName("calib_wl_spinner")
        self.calib_layout.addWidget(self.calib_wl_spinner, 0, QtCore.Qt.AlignHCenter)
        self.set_home_wl_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_home_wl_button.sizePolicy().hasHeightForWidth())
        self.set_home_wl_button.setSizePolicy(sizePolicy)
        self.set_home_wl_button.setObjectName("set_home_wl_button")
        self.calib_layout.addWidget(self.set_home_wl_button, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.set_mono_group_2, 5, 1, 1, 4)
        self.tab_container.addTab(self.set_mono_tab, "")
        self.setup_tab = QtWidgets.QWidget()
        self.setup_tab.setObjectName("setup_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.setup_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 591, 371))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.setup_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.setup_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.setup_grid_layout.setObjectName("setup_grid_layout")
        self.setup_groupBox_4 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.setup_groupBox_4.setTitle("")
        self.setup_groupBox_4.setObjectName("setup_groupBox_4")
        self.speed_label = QtWidgets.QLabel(self.setup_groupBox_4)
        self.speed_label.setGeometry(QtCore.QRect(120, 30, 51, 21))
        self.speed_label.setObjectName("speed_label")
        self.speed_set_button = QtWidgets.QPushButton(self.setup_groupBox_4)
        self.speed_set_button.setGeometry(QtCore.QRect(220, 34, 71, 21))
        self.speed_set_button.setMaximumSize(QtCore.QSize(100, 25))
        self.speed_set_button.setObjectName("speed_set_button")
        self.speed_value_spinner = QtWidgets.QDoubleSpinBox(self.setup_groupBox_4)
        self.speed_value_spinner.setGeometry(QtCore.QRect(340, 30, 55, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_value_spinner.sizePolicy().hasHeightForWidth())
        self.speed_value_spinner.setSizePolicy(sizePolicy)
        self.speed_value_spinner.setMaximumSize(QtCore.QSize(100, 25))
        self.speed_value_spinner.setDecimals(1)
        self.speed_value_spinner.setMaximum(500.0)
        self.speed_value_spinner.setProperty("value", 100.0)
        self.speed_value_spinner.setObjectName("speed_value_spinner")
        self.setup_grid_layout.addWidget(self.setup_groupBox_4, 6, 1, 1, 2)
        self.nudge_stop_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nudge_stop_button.sizePolicy().hasHeightForWidth())
        self.nudge_stop_button.setSizePolicy(sizePolicy)
        self.nudge_stop_button.setMaximumSize(QtCore.QSize(500, 30))
        self.nudge_stop_button.setObjectName("nudge_stop_button")
        self.setup_grid_layout.addWidget(self.nudge_stop_button, 7, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.setup_grid_layout.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.setup_grid_layout.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.setup_grid_layout.addItem(spacerItem8, 2, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.setup_grid_layout.addItem(spacerItem9, 9, 2, 1, 1)
        self.setup_group_1 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.setup_group_1.setTitle("")
        self.setup_group_1.setObjectName("setup_group_1")
        self.setup_current_wl_label = QtWidgets.QLabel(self.setup_group_1)
        self.setup_current_wl_label.setGeometry(QtCore.QRect(40, 30, 114, 22))
        self.setup_current_wl_label.setObjectName("setup_current_wl_label")
        self.current_wl_output_lineedit = QtWidgets.QLineEdit(self.setup_group_1)
        self.current_wl_output_lineedit.setEnabled(False)
        self.current_wl_output_lineedit.setGeometry(QtCore.QRect(340, 30, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_wl_output_lineedit.sizePolicy().hasHeightForWidth())
        self.current_wl_output_lineedit.setSizePolicy(sizePolicy)
        self.current_wl_output_lineedit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.current_wl_output_lineedit.setObjectName("current_wl_output_lineedit")
        self.setup_grid_layout.addWidget(self.setup_group_1, 1, 1, 1, 2)
        self.setup_groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.setup_groupBox_2.setTitle("")
        self.setup_groupBox_2.setObjectName("setup_groupBox_2")
        self.goto_wl_label = QtWidgets.QLabel(self.setup_groupBox_2)
        self.goto_wl_label.setGeometry(QtCore.QRect(90, 20, 107, 28))
        self.goto_wl_label.setObjectName("goto_wl_label")
        self.goto_wl_button = QtWidgets.QPushButton(self.setup_groupBox_2)
        self.goto_wl_button.setGeometry(QtCore.QRect(220, 20, 71, 25))
        self.goto_wl_button.setObjectName("goto_wl_button")
        self.goto_wl_spinner = QtWidgets.QDoubleSpinBox(self.setup_groupBox_2)
        self.goto_wl_spinner.setGeometry(QtCore.QRect(340, 20, 55, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goto_wl_spinner.sizePolicy().hasHeightForWidth())
        self.goto_wl_spinner.setSizePolicy(sizePolicy)
        self.goto_wl_spinner.setMaximumSize(QtCore.QSize(100, 25))
        self.goto_wl_spinner.setDecimals(1)
        self.goto_wl_spinner.setMaximum(3000.0)
        self.goto_wl_spinner.setProperty("value", 500.0)
        self.goto_wl_spinner.setObjectName("goto_wl_spinner")
        self.setup_grid_layout.addWidget(self.setup_groupBox_2, 2, 1, 1, 2)
        self.setup_groupBox_3 = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.setup_groupBox_3.setTitle("")
        self.setup_groupBox_3.setObjectName("setup_groupBox_3")
        self.nudge_label = QtWidgets.QLabel(self.setup_groupBox_3)
        self.nudge_label.setGeometry(QtCore.QRect(60, 15, 107, 31))
        self.nudge_label.setObjectName("nudge_label")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.setup_groupBox_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(280, 20, 153, 29))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nudge_down_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.nudge_down_button.setMaximumSize(QtCore.QSize(25, 25))
        self.nudge_down_button.setObjectName("nudge_down_button")
        self.horizontalLayout.addWidget(self.nudge_down_button)
        self.nudge_amount_spinner = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nudge_amount_spinner.sizePolicy().hasHeightForWidth())
        self.nudge_amount_spinner.setSizePolicy(sizePolicy)
        self.nudge_amount_spinner.setMaximumSize(QtCore.QSize(75, 25))
        self.nudge_amount_spinner.setDecimals(1)
        self.nudge_amount_spinner.setMaximum(500.0)
        self.nudge_amount_spinner.setProperty("value", 10.0)
        self.nudge_amount_spinner.setObjectName("nudge_amount_spinner")
        self.horizontalLayout.addWidget(self.nudge_amount_spinner)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.nudge_up_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.nudge_up_button.setMaximumSize(QtCore.QSize(25, 25))
        self.nudge_up_button.setObjectName("nudge_up_button")
        self.horizontalLayout_2.addWidget(self.nudge_up_button)
        self.setup_grid_layout.addWidget(self.setup_groupBox_3, 4, 1, 1, 2)
        self.tab_container.addTab(self.setup_tab, "")
        self.scan_tab = QtWidgets.QWidget()
        self.scan_tab.setObjectName("scan_tab")
        self.scan_wl_box = QtWidgets.QGroupBox(self.scan_tab)
        self.scan_wl_box.setGeometry(QtCore.QRect(10, 10, 251, 131))
        self.scan_wl_box.setTitle("")
        self.scan_wl_box.setObjectName("scan_wl_box")
        self.scan_start_wl_spinner = QtWidgets.QDoubleSpinBox(self.scan_wl_box)
        self.scan_start_wl_spinner.setGeometry(QtCore.QRect(90, 30, 131, 22))
        self.scan_start_wl_spinner.setDecimals(1)
        self.scan_start_wl_spinner.setMaximum(3000.0)
        self.scan_start_wl_spinner.setProperty("value", 300.0)
        self.scan_start_wl_spinner.setObjectName("scan_start_wl_spinner")
        self.scan_stop_wl_spinner = QtWidgets.QDoubleSpinBox(self.scan_wl_box)
        self.scan_stop_wl_spinner.setGeometry(QtCore.QRect(90, 80, 131, 22))
        self.scan_stop_wl_spinner.setDecimals(1)
        self.scan_stop_wl_spinner.setMaximum(3000.0)
        self.scan_stop_wl_spinner.setProperty("value", 800.0)
        self.scan_stop_wl_spinner.setObjectName("scan_stop_wl_spinner")
        self.scan_start_wl_label = QtWidgets.QLabel(self.scan_wl_box)
        self.scan_start_wl_label.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.scan_start_wl_label.setObjectName("scan_start_wl_label")
        self.scan_stop_wl_label = QtWidgets.QLabel(self.scan_wl_box)
        self.scan_stop_wl_label.setGeometry(QtCore.QRect(10, 80, 55, 16))
        self.scan_stop_wl_label.setObjectName("scan_stop_wl_label")
        self.step_pause_box = QtWidgets.QGroupBox(self.scan_tab)
        self.step_pause_box.setGeometry(QtCore.QRect(10, 150, 251, 141))
        self.step_pause_box.setTitle("")
        self.step_pause_box.setObjectName("step_pause_box")
        self.scan_pause_spinner = QtWidgets.QDoubleSpinBox(self.step_pause_box)
        self.scan_pause_spinner.setGeometry(QtCore.QRect(90, 90, 131, 22))
        self.scan_pause_spinner.setMinimum(-1.0)
        self.scan_pause_spinner.setMaximum(1000.0)
        self.scan_pause_spinner.setProperty("value", 1.0)
        self.scan_pause_spinner.setObjectName("scan_pause_spinner")
        self.scan_step_spinner = QtWidgets.QDoubleSpinBox(self.step_pause_box)
        self.scan_step_spinner.setGeometry(QtCore.QRect(90, 40, 131, 22))
        self.scan_step_spinner.setDecimals(1)
        self.scan_step_spinner.setMaximum(1000.0)
        self.scan_step_spinner.setProperty("value", 10.0)
        self.scan_step_spinner.setObjectName("scan_step_spinner")
        self.scan_step_label = QtWidgets.QLabel(self.step_pause_box)
        self.scan_step_label.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.scan_step_label.setObjectName("scan_step_label")
        self.scan_pause_label = QtWidgets.QLabel(self.step_pause_box)
        self.scan_pause_label.setGeometry(QtCore.QRect(10, 90, 55, 16))
        self.scan_pause_label.setObjectName("scan_pause_label")
        self.scan_cycles_spinner = QtWidgets.QSpinBox(self.scan_tab)
        self.scan_cycles_spinner.setGeometry(QtCore.QRect(80, 310, 91, 21))
        self.scan_cycles_spinner.setMaximum(1000)
        self.scan_cycles_spinner.setProperty("value", 1)
        self.scan_cycles_spinner.setObjectName("scan_cycles_spinner")
        self.scan_cycles_label = QtWidgets.QLabel(self.scan_tab)
        self.scan_cycles_label.setGeometry(QtCore.QRect(190, 310, 55, 16))
        self.scan_cycles_label.setObjectName("scan_cycles_label")
        self.scan_start_button = QtWidgets.QPushButton(self.scan_tab)
        self.scan_start_button.setGeometry(QtCore.QRect(380, 120, 93, 28))
        self.scan_start_button.setObjectName("scan_start_button")
        self.scan_stop_button = QtWidgets.QPushButton(self.scan_tab)
        self.scan_stop_button.setGeometry(QtCore.QRect(380, 160, 93, 28))
        self.scan_stop_button.setObjectName("scan_stop_button")
        self.tab_container.addTab(self.scan_tab, "")
        self.debug_tab = QtWidgets.QWidget()
        self.debug_tab.setObjectName("debug_tab")
        self.debug_write_str_textbox = QtWidgets.QPlainTextEdit(self.debug_tab)
        self.debug_write_str_textbox.setGeometry(QtCore.QRect(60, 70, 104, 87))
        self.debug_write_str_textbox.setObjectName("debug_write_str_textbox")
        self.debug_read_textbox = QtWidgets.QPlainTextEdit(self.debug_tab)
        self.debug_read_textbox.setEnabled(False)
        self.debug_read_textbox.setGeometry(QtCore.QRect(60, 200, 401, 87))
        self.debug_read_textbox.setObjectName("debug_read_textbox")
        self.debug_write_button = QtWidgets.QPushButton(self.debug_tab)
        self.debug_write_button.setGeometry(QtCore.QRect(60, 40, 41, 28))
        self.debug_write_button.setObjectName("debug_write_button")
        self.debug_read_label = QtWidgets.QLabel(self.debug_tab)
        self.debug_read_label.setGeometry(QtCore.QRect(60, 180, 55, 16))
        self.debug_read_label.setObjectName("debug_read_label")
        self.debug_checkbox = QtWidgets.QCheckBox(self.debug_tab)
        self.debug_checkbox.setGeometry(QtCore.QRect(270, 70, 111, 17))
        self.debug_checkbox.setObjectName("debug_checkbox")
        self.tab_container.addTab(self.debug_tab, "")
        self.gridLayout_2.addWidget(self.tab_container, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_container.setCurrentIndex(3)
        self.groove_density_combobox.activated['QString'].connect(MainWindow.set_groove_density)
        self.set_home_wl_button.clicked.connect(MainWindow.clicked_home_button)
        self.mono_initialize_button.clicked.connect(MainWindow.clicked_initialize_button)
        self.backlash_checkbox.stateChanged['int'].connect(MainWindow.state_changed_bl_compensation)
        self.debug_write_button.clicked.connect(MainWindow.clicked_debug_write_button)
        self.visa_resource_combobox.activated['QString'].connect(MainWindow.set_com_port)
        self.nudge_up_button.clicked.connect(MainWindow.clicked_nudge_up_button)
        self.goto_wl_button.clicked.connect(MainWindow.clicked_go_to_wl_button)
        self.nudge_stop_button.clicked.connect(MainWindow.clicked_stop_nudge_button)
        self.nudge_down_button.clicked.connect(MainWindow.clicked_nudge_down_button)
        self.speed_set_button.clicked.connect(MainWindow.clicked_speed_set_button)
        self.scan_start_button.clicked.connect(MainWindow.clicked_start_scan_button)
        self.scan_stop_button.clicked.connect(MainWindow.clicked_stop_scan_button)
        self.debug_checkbox.stateChanged['int'].connect(MainWindow.state_changed_debug_checkbox)
        self.backlash_amount_spinner.valueChanged['QString'].connect(MainWindow.value_changed_backlash_spinner)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tab_container, self.visa_resource_combobox)
        MainWindow.setTabOrder(self.visa_resource_combobox, self.groove_density_combobox)
        MainWindow.setTabOrder(self.groove_density_combobox, self.calib_wl_spinner)
        MainWindow.setTabOrder(self.calib_wl_spinner, self.backlash_checkbox)
        MainWindow.setTabOrder(self.backlash_checkbox, self.set_home_wl_button)
        MainWindow.setTabOrder(self.set_home_wl_button, self.backlash_amount_spinner)
        MainWindow.setTabOrder(self.backlash_amount_spinner, self.mono_initialize_button)
        MainWindow.setTabOrder(self.mono_initialize_button, self.current_wl_output_lineedit)
        MainWindow.setTabOrder(self.current_wl_output_lineedit, self.goto_wl_button)
        MainWindow.setTabOrder(self.goto_wl_button, self.goto_wl_spinner)
        MainWindow.setTabOrder(self.goto_wl_spinner, self.nudge_down_button)
        MainWindow.setTabOrder(self.nudge_down_button, self.nudge_amount_spinner)
        MainWindow.setTabOrder(self.nudge_amount_spinner, self.nudge_up_button)
        MainWindow.setTabOrder(self.nudge_up_button, self.speed_set_button)
        MainWindow.setTabOrder(self.speed_set_button, self.speed_value_spinner)
        MainWindow.setTabOrder(self.speed_value_spinner, self.nudge_stop_button)
        MainWindow.setTabOrder(self.nudge_stop_button, self.scan_start_wl_spinner)
        MainWindow.setTabOrder(self.scan_start_wl_spinner, self.scan_stop_wl_spinner)
        MainWindow.setTabOrder(self.scan_stop_wl_spinner, self.scan_step_spinner)
        MainWindow.setTabOrder(self.scan_step_spinner, self.scan_pause_spinner)
        MainWindow.setTabOrder(self.scan_pause_spinner, self.scan_cycles_spinner)
        MainWindow.setTabOrder(self.scan_cycles_spinner, self.scan_start_button)
        MainWindow.setTabOrder(self.scan_start_button, self.scan_stop_button)
        MainWindow.setTabOrder(self.scan_stop_button, self.debug_write_button)
        MainWindow.setTabOrder(self.debug_write_button, self.debug_write_str_textbox)
        MainWindow.setTabOrder(self.debug_write_str_textbox, self.debug_read_textbox)
        MainWindow.setTabOrder(self.debug_read_textbox, self.debug_checkbox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.com_port_label.setText(_translate("MainWindow", "Communication Port"))
        self.groove_density_label.setText(_translate("MainWindow", "Grating Groove Density (gr/mm)"))
        self.groove_density_combobox.setItemText(0, _translate("MainWindow", "2400"))
        self.groove_density_combobox.setItemText(1, _translate("MainWindow", "1800"))
        self.groove_density_combobox.setItemText(2, _translate("MainWindow", "1200"))
        self.groove_density_combobox.setItemText(3, _translate("MainWindow", "600"))
        self.groove_density_combobox.setItemText(4, _translate("MainWindow", "300"))
        self.groove_density_combobox.setItemText(5, _translate("MainWindow", "150"))
        self.mono_initialize_button.setText(_translate("MainWindow", "Initialize and Home Monochromator"))
        self.backlash_label.setText(_translate("MainWindow", "Compensate for Backlash"))
        self.backlash_checkbox.setText(_translate("MainWindow", "On"))
        self.backlash_amount_label.setText(_translate("MainWindow", "Amount (nm)"))
        self.calib_wl_label.setText(_translate("MainWindow", "Calibration Wavelength (nm)"))
        self.set_home_wl_button.setText(_translate("MainWindow", "Set Home"))
        self.tab_container.setTabText(self.tab_container.indexOf(self.set_mono_tab), _translate("MainWindow", "Set Mono"))
        self.speed_label.setText(_translate("MainWindow", "Speed"))
        self.speed_set_button.setText(_translate("MainWindow", "Set"))
        self.nudge_stop_button.setText(_translate("MainWindow", "Stop"))
        self.setup_current_wl_label.setText(_translate("MainWindow", "Current Wavelength"))
        self.goto_wl_label.setText(_translate("MainWindow", "Wavelength"))
        self.goto_wl_button.setText(_translate("MainWindow", "Go"))
        self.nudge_label.setText(_translate("MainWindow", "Nudge Wavelength"))
        self.nudge_down_button.setText(_translate("MainWindow", "<"))
        self.nudge_up_button.setText(_translate("MainWindow", ">"))
        self.tab_container.setTabText(self.tab_container.indexOf(self.setup_tab), _translate("MainWindow", "Setup"))
        self.scan_start_wl_label.setText(_translate("MainWindow", "Start WL"))
        self.scan_stop_wl_label.setText(_translate("MainWindow", "Stop WL"))
        self.scan_step_label.setText(_translate("MainWindow", "Step (nm)"))
        self.scan_pause_label.setText(_translate("MainWindow", "Pause (s)"))
        self.scan_cycles_label.setText(_translate("MainWindow", "Cycles"))
        self.scan_start_button.setText(_translate("MainWindow", "Start Scan"))
        self.scan_stop_button.setText(_translate("MainWindow", "Stop Scan"))
        self.tab_container.setTabText(self.tab_container.indexOf(self.scan_tab), _translate("MainWindow", "Scan"))
        self.debug_write_button.setText(_translate("MainWindow", "Write"))
        self.debug_read_label.setText(_translate("MainWindow", "Read"))
        self.debug_checkbox.setText(_translate("MainWindow", "Debug Mode"))
        self.tab_container.setTabText(self.tab_container.indexOf(self.debug_tab), _translate("MainWindow", "Debug"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Settings.setText(_translate("MainWindow", "Save Settings"))
