# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ryan/AppData/Local/Temp/settings_widget_UIhacexv.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 609)
        self.tab_widget = QtWidgets.QTabWidget(Form)
        self.tab_widget.setGeometry(QtCore.QRect(10, 10, 631, 501))
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.general_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 301, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.sr844_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.sr844_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sr844_checkbox.setText("")
        self.sr844_checkbox.setObjectName("sr844_checkbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sr844_checkbox)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.sr830_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.sr830_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sr830_checkbox.setText("")
        self.sr830_checkbox.setObjectName("sr830_checkbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sr830_checkbox)
        self.md2000_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.md2000_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.md2000_checkbox.setText("")
        self.md2000_checkbox.setObjectName("md2000_checkbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.md2000_checkbox)
        self.cg635_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cg635_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cg635_checkbox.setText("")
        self.cg635_checkbox.setObjectName("cg635_checkbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cg635_checkbox)
        self.smb100a_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.smb100a_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.smb100a_checkbox.setText("")
        self.smb100a_checkbox.setObjectName("smb100a_checkbox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.smb100a_checkbox)
        self.montana_instr_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.montana_instr_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.montana_instr_checkbox.setText("")
        self.montana_instr_checkbox.setObjectName("montana_instr_checkbox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.montana_instr_checkbox)
        self.toptica_checkbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.toptica_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toptica_checkbox.setText("")
        self.toptica_checkbox.setObjectName("toptica_checkbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.toptica_checkbox)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.tab_widget.addTab(self.general_tab, "")
        self.lockin_tab = QtWidgets.QWidget()
        self.lockin_tab.setObjectName("lockin_tab")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.lockin_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(399, 9, 211, 205))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.auto_sens_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.auto_sens_btn.setObjectName("auto_sens_btn")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.auto_sens_btn)
        self.auto_creserve_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.auto_creserve_btn.setObjectName("auto_creserve_btn")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.auto_creserve_btn)
        self.auto_wreserve_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.auto_wreserve_btn.setObjectName("auto_wreserve_btn")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.auto_wreserve_btn)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton_2)
        self.auto_dyn_reserve_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.auto_dyn_reserve_btn.setObjectName("auto_dyn_reserve_btn")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.auto_dyn_reserve_btn)
        self.scrollArea = QtWidgets.QScrollArea(self.lockin_tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 381, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -185, 358, 634))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 13, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.filter_slope_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.filter_slope_combobox.setObjectName("filter_slope_combobox")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.gridLayout.addWidget(self.filter_slope_combobox, 7, 1, 1, 1)
        self.ref_impedance_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.ref_impedance_combobox.setObjectName("ref_impedance_combobox")
        self.ref_impedance_combobox.addItem("")
        self.ref_impedance_combobox.addItem("")
        self.gridLayout.addWidget(self.ref_impedance_combobox, 14, 1, 1, 1)
        self.sr844_gpib_address_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.sr844_gpib_address_spinner.setObjectName("sr844_gpib_address_spinner")
        self.gridLayout.addWidget(self.sr844_gpib_address_spinner, 2, 1, 1, 1)
        self.sampling_rate_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sampling_rate_combobox.setObjectName("sampling_rate_combobox")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.gridLayout.addWidget(self.sampling_rate_combobox, 12, 1, 1, 1)
        self.dynamic_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.dynamic_reserve_combobox.setObjectName("dynamic_reserve_combobox")
        self.dynamic_reserve_combobox.addItem("")
        self.dynamic_reserve_combobox.addItem("")
        self.dynamic_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.dynamic_reserve_combobox, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 19, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.sr830_gpib_address_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.sr830_gpib_address_spinner.setObjectName("sr830_gpib_address_spinner")
        self.gridLayout.addWidget(self.sr830_gpib_address_spinner, 3, 1, 1, 1)
        self.expand_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.expand_combobox.setObjectName("expand_combobox")
        self.expand_combobox.addItem("")
        self.expand_combobox.addItem("")
        self.expand_combobox.addItem("")
        self.gridLayout.addWidget(self.expand_combobox, 19, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 15, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 14, 0, 1, 1)
        self.ref_source_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.ref_source_combobox.setObjectName("ref_source_combobox")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.gridLayout.addWidget(self.ref_source_combobox, 15, 1, 1, 1)
        self.wide_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.wide_reserve_combobox.setObjectName("wide_reserve_combobox")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.wide_reserve_combobox, 9, 1, 1, 1)
        self.close_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.close_reserve_combobox.setObjectName("close_reserve_combobox")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.close_reserve_combobox, 10, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 16, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.lockin_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.lockin_com_port_spinner.setObjectName("lockin_com_port_spinner")
        self.gridLayout.addWidget(self.lockin_com_port_spinner, 1, 1, 1, 1)
        self.lockin_model_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.lockin_model_combobox.setObjectName("lockin_model_combobox")
        self.lockin_model_combobox.addItem("")
        self.lockin_model_combobox.addItem("")
        self.gridLayout.addWidget(self.lockin_model_combobox, 0, 1, 1, 1)
        self.sr844_harmonic_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sr844_harmonic_combobox.setObjectName("sr844_harmonic_combobox")
        self.sr844_harmonic_combobox.addItem("")
        self.sr844_harmonic_combobox.addItem("")
        self.gridLayout.addWidget(self.sr844_harmonic_combobox, 16, 1, 1, 1)
        self.sensitivity_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sensitivity_combobox.setObjectName("sensitivity_combobox")
        self.sensitivity_combobox.addItem("")
        self.gridLayout.addWidget(self.sensitivity_combobox, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 21, 0, 1, 2)
        self.phase_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.phase_spinner.setObjectName("phase_spinner")
        self.gridLayout.addWidget(self.phase_spinner, 18, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.time_constant_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.time_constant_combobox.setObjectName("time_constant_combobox")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.gridLayout.addWidget(self.time_constant_combobox, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 18, 0, 1, 1)
        self.outputs_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.outputs_combobox.setObjectName("outputs_combobox")
        self.outputs_combobox.addItem("")
        self.outputs_combobox.addItem("")
        self.outputs_combobox.addItem("")
        self.gridLayout.addWidget(self.outputs_combobox, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 11, 0, 1, 1)
        self.save_as_dflt_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.save_as_dflt_btn.setObjectName("save_as_dflt_btn")
        self.gridLayout.addWidget(self.save_as_dflt_btn, 20, 0, 1, 2)
        self.input_impedance_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.input_impedance_combobox.setObjectName("input_impedance_combobox")
        self.input_impedance_combobox.addItem("")
        self.input_impedance_combobox.addItem("")
        self.gridLayout.addWidget(self.input_impedance_combobox, 13, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 17, 0, 1, 1)
        self.harmonic_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.harmonic_spinner.setObjectName("harmonic_spinner")
        self.gridLayout.addWidget(self.harmonic_spinner, 17, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tab_widget.addTab(self.lockin_tab, "")
        self.mono_tab = QtWidgets.QWidget()
        self.mono_tab.setObjectName("mono_tab")
        self.tab_widget.addTab(self.mono_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab_widget.addTab(self.tab, "")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 510, 629, 91))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancel_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_2.addWidget(self.cancel_btn, 1, 2, 1, 1)
        self.set_all_params_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_all_params_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.set_all_params_btn.setObjectName("set_all_params_btn")
        self.gridLayout_2.addWidget(self.set_all_params_btn, 1, 1, 1, 1)
        self.set_tab_params_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_tab_params_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.set_tab_params_btn.setObjectName("set_tab_params_btn")
        self.gridLayout_2.addWidget(self.set_tab_params_btn, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 2)

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(0)
        self.save_as_dflt_btn.clicked.connect(Form.save_as_dflt_btn_clicked)
        self.set_all_params_btn.clicked.connect(Form.set_all_params_btn_clicked)
        self.cancel_btn.clicked.connect(Form.cancel_btn_clicked)
        self.auto_sens_btn.clicked.connect(Form.auto_sens_btn_clicked)
        self.lockin_model_combobox.currentIndexChanged['int'].connect(Form.lockin_model_changed)
        self.set_tab_params_btn.clicked.connect(Form.set_tab_params_btn_clicked)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_21.setText(_translate("Form", "Connected Instruments"))
        self.label_22.setText(_translate("Form", "SR844 Lock-in Amplifier"))
        self.label_23.setText(_translate("Form", "SR830 Lock-in Amplifier"))
        self.label_24.setText(_translate("Form", "Monochromator Driver (MD2000)"))
        self.label_25.setText(_translate("Form", "Clock Generator (CG 635)"))
        self.label_26.setText(_translate("Form", "RF (Microwave) Source (SMB100A)"))
        self.label_27.setText(_translate("Form", "Cryostat/Magnet (Montana Instruments)"))
        self.label_28.setText(_translate("Form", "Pump Laser (Toptica iBeam Smart)"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("Form", "General"))
        self.auto_sens_btn.setText(_translate("Form", "Auto Sensitivity Adjust"))
        self.auto_creserve_btn.setText(_translate("Form", "Auto Close Reserve (SR844)"))
        self.auto_wreserve_btn.setText(_translate("Form", "Auto Wide Reserve (SR844)"))
        self.pushButton.setText(_translate("Form", "Auto Phase"))
        self.pushButton_2.setText(_translate("Form", "Auto Offset X/Y"))
        self.auto_dyn_reserve_btn.setText(_translate("Form", "Auto Reserve (SR830)"))
        self.label_15.setText(_translate("Form", "Filter Slope"))
        self.label_14.setText(_translate("Form", "GPIB Address (SR844)"))
        self.label_6.setText(_translate("Form", "Input Impedance"))
        self.label_13.setText(_translate("Form", "Com Port"))
        self.label_3.setText(_translate("Form", "Sensitivity"))
        self.filter_slope_combobox.setItemText(0, _translate("Form", "No Filter"))
        self.filter_slope_combobox.setItemText(1, _translate("Form", "6 dB/Octave"))
        self.filter_slope_combobox.setItemText(2, _translate("Form", "12 dB/Octave"))
        self.filter_slope_combobox.setItemText(3, _translate("Form", "18 dB/Octave"))
        self.filter_slope_combobox.setItemText(4, _translate("Form", "24 dB/Octave"))
        self.ref_impedance_combobox.setItemText(0, _translate("Form", "50 Ω"))
        self.ref_impedance_combobox.setItemText(1, _translate("Form", "10 kΩ / 40 pF"))
        self.sampling_rate_combobox.setItemText(0, _translate("Form", "0.0625 (16 s)"))
        self.sampling_rate_combobox.setItemText(1, _translate("Form", "0.125 (8 s)"))
        self.sampling_rate_combobox.setItemText(2, _translate("Form", "0.250 (4 s)"))
        self.sampling_rate_combobox.setItemText(3, _translate("Form", "0.500 (2 s)"))
        self.sampling_rate_combobox.setItemText(4, _translate("Form", "1"))
        self.sampling_rate_combobox.setItemText(5, _translate("Form", "2"))
        self.sampling_rate_combobox.setItemText(6, _translate("Form", "4"))
        self.sampling_rate_combobox.setItemText(7, _translate("Form", "8"))
        self.sampling_rate_combobox.setItemText(8, _translate("Form", "16"))
        self.sampling_rate_combobox.setItemText(9, _translate("Form", "32"))
        self.sampling_rate_combobox.setItemText(10, _translate("Form", "64"))
        self.sampling_rate_combobox.setItemText(11, _translate("Form", "128"))
        self.sampling_rate_combobox.setItemText(12, _translate("Form", "256"))
        self.sampling_rate_combobox.setItemText(13, _translate("Form", "512"))
        self.sampling_rate_combobox.setItemText(14, _translate("Form", "Trigger"))
        self.dynamic_reserve_combobox.setItemText(0, _translate("Form", "High Reserve (Max)"))
        self.dynamic_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.dynamic_reserve_combobox.setItemText(2, _translate("Form", "Low Noise (Min)"))
        self.label_4.setText(_translate("Form", "Time Constant"))
        self.label_8.setText(_translate("Form", "Expand"))
        self.label_5.setText(_translate("Form", "Sampling Rate"))
        self.label.setText(_translate("Form", "Wide Reserve (SR844)"))
        self.expand_combobox.setItemText(0, _translate("Form", "x1 (off)"))
        self.expand_combobox.setItemText(1, _translate("Form", "x10"))
        self.expand_combobox.setItemText(2, _translate("Form", "x100"))
        self.label_10.setText(_translate("Form", "Reference Source"))
        self.label_9.setText(_translate("Form", "Reference Impedance"))
        self.ref_source_combobox.setItemText(0, _translate("Form", "External"))
        self.ref_source_combobox.setItemText(1, _translate("Form", "Internal"))
        self.ref_source_combobox.setItemText(2, _translate("Form", "2F (External Ref)"))
        self.ref_source_combobox.setItemText(3, _translate("Form", "2F (Internal Ref)"))
        self.wide_reserve_combobox.setItemText(0, _translate("Form", "High"))
        self.wide_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.wide_reserve_combobox.setItemText(2, _translate("Form", "Low Noise"))
        self.wide_reserve_combobox.setItemText(3, _translate("Form", "Auto"))
        self.close_reserve_combobox.setItemText(0, _translate("Form", "High"))
        self.close_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.close_reserve_combobox.setItemText(2, _translate("Form", "Low Noise"))
        self.close_reserve_combobox.setItemText(3, _translate("Form", "Auto"))
        self.label_19.setText(_translate("Form", "2F Detect Mode (SR844)"))
        self.label_16.setText(_translate("Form", "GPIB Address (SR830)"))
        self.lockin_model_combobox.setItemText(0, _translate("Form", "SR844 (25 kHz-200 MHz)"))
        self.lockin_model_combobox.setItemText(1, _translate("Form", "SR830 (1 mHz-102 kHz)"))
        self.sr844_harmonic_combobox.setItemText(0, _translate("Form", "Off"))
        self.sr844_harmonic_combobox.setItemText(1, _translate("Form", "On"))
        self.sensitivity_combobox.setItemText(0, _translate("Form", "UNDER CONSTRUCTION"))
        self.label_12.setText(_translate("Form", "Note: Sensitivity default cannot be changed (damage risk)"))
        self.label_17.setText(_translate("Form", "Lock-in Model"))
        self.time_constant_combobox.setItemText(0, _translate("Form", "100  μs"))
        self.time_constant_combobox.setItemText(1, _translate("Form", "300  μs"))
        self.time_constant_combobox.setItemText(2, _translate("Form", "1     ms"))
        self.time_constant_combobox.setItemText(3, _translate("Form", "3     ms"))
        self.time_constant_combobox.setItemText(4, _translate("Form", "10   ms"))
        self.time_constant_combobox.setItemText(5, _translate("Form", "30   ms"))
        self.time_constant_combobox.setItemText(6, _translate("Form", "100 ms"))
        self.time_constant_combobox.setItemText(7, _translate("Form", "300 ms"))
        self.time_constant_combobox.setItemText(8, _translate("Form", "1        s"))
        self.time_constant_combobox.setItemText(9, _translate("Form", "3        s"))
        self.time_constant_combobox.setItemText(10, _translate("Form", "10      s"))
        self.time_constant_combobox.setItemText(11, _translate("Form", "30      s"))
        self.time_constant_combobox.setItemText(12, _translate("Form", "100    s"))
        self.time_constant_combobox.setItemText(13, _translate("Form", "300    s"))
        self.time_constant_combobox.setItemText(14, _translate("Form", "1      ks"))
        self.time_constant_combobox.setItemText(15, _translate("Form", "3      ks"))
        self.time_constant_combobox.setItemText(16, _translate("Form", "10    ks"))
        self.time_constant_combobox.setItemText(17, _translate("Form", "30    ks"))
        self.label_2.setText(_translate("Form", "Outputs"))
        self.label_11.setText(_translate("Form", "Phase"))
        self.outputs_combobox.setItemText(0, _translate("Form", "R / θ (V/degrees)"))
        self.outputs_combobox.setItemText(1, _translate("Form", "X / Y"))
        self.outputs_combobox.setItemText(2, _translate("Form", "Manual"))
        self.label_18.setText(_translate("Form", "Dynamic Reserve (SR830)"))
        self.save_as_dflt_btn.setText(_translate("Form", "Save as Default Values"))
        self.input_impedance_combobox.setItemText(0, _translate("Form", "50 Ω"))
        self.input_impedance_combobox.setItemText(1, _translate("Form", "1 MΩ / 30 pF"))
        self.label_7.setText(_translate("Form", "Close Reserve (SR844)"))
        self.label_20.setText(_translate("Form", "Harmonic (SR830)"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.lockin_tab), _translate("Form", "Lock-in"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.mono_tab), _translate("Form", "Monochromator"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("Form", "Rohde && Schwarz"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))
        self.set_all_params_btn.setText(_translate("Form", "All Tabs"))
        self.set_tab_params_btn.setText(_translate("Form", "Current Tab"))
        self.label_29.setText(_translate("Form", "Set Parameters"))
