# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ryan/AppData/Local/Temp/expt_control_UIBhwQGk.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1427, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scroll_area_control_panel = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area_control_panel.setMaximumSize(QtCore.QSize(500, 16777215))
        self.scroll_area_control_panel.setWidgetResizable(True)
        self.scroll_area_control_panel.setObjectName("scroll_area_control_panel")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 477, 1388))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autosave_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.autosave_checkbox.setChecked(True)
        self.autosave_checkbox.setObjectName("autosave_checkbox")
        self.verticalLayout.addWidget(self.autosave_checkbox)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.experiment_presets_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.experiment_presets_combobox.setObjectName("experiment_presets_combobox")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.experiment_presets_combobox.addItem("")
        self.verticalLayout.addWidget(self.experiment_presets_combobox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setMidLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.variable_1_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.variable_1_combobox.setMinimumSize(QtCore.QSize(300, 0))
        self.variable_1_combobox.setObjectName("variable_1_combobox")
        self.variable_1_combobox.addItem("")
        self.variable_1_combobox.setItemText(0, "")
        self.variable_1_combobox.addItem("")
        self.variable_1_combobox.addItem("")
        self.variable_1_combobox.addItem("")
        self.variable_1_combobox.addItem("")
        self.variable_1_combobox.addItem("")
        self.verticalLayout.addWidget(self.variable_1_combobox)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 3, 1, 1)
        self.num_steps_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.num_steps_spinner.setMinimum(1)
        self.num_steps_spinner.setMaximum(10000)
        self.num_steps_spinner.setObjectName("num_steps_spinner")
        self.gridLayout_3.addWidget(self.num_steps_spinner, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 3, 1, 1)
        self.sweep_start_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sweep_start_spinner.setMinimum(-100000.0)
        self.sweep_start_spinner.setMaximum(100000.0)
        self.sweep_start_spinner.setObjectName("sweep_start_spinner")
        self.gridLayout_3.addWidget(self.sweep_start_spinner, 1, 2, 1, 1)
        self.steps_display = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.steps_display.setMaximumSize(QtCore.QSize(100, 16777215))
        self.steps_display.setObjectName("steps_display")
        self.gridLayout_3.addWidget(self.steps_display, 0, 4, 4, 1)
        self.step_size_display = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.step_size_display.setEnabled(False)
        self.step_size_display.setMaximumSize(QtCore.QSize(100, 16777215))
        self.step_size_display.setObjectName("step_size_display")
        self.gridLayout_3.addWidget(self.step_size_display, 3, 3, 1, 1)
        self.sweep_end_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sweep_end_spinner.setMinimum(-100000000.0)
        self.sweep_end_spinner.setMaximum(100000000.0)
        self.sweep_end_spinner.setObjectName("sweep_end_spinner")
        self.gridLayout_3.addWidget(self.sweep_end_spinner, 1, 3, 1, 1)
        self.log_spacing_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.log_spacing_checkbox.setObjectName("log_spacing_checkbox")
        self.gridLayout_3.addWidget(self.log_spacing_checkbox, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(3)
        self.frame_4.setMidLineWidth(5)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 0, 1, 1)
        self.averaging_time_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.averaging_time_spinner.setMaximum(1000.0)
        self.averaging_time_spinner.setSingleStep(0.1)
        self.averaging_time_spinner.setProperty("value", 0.5)
        self.averaging_time_spinner.setObjectName("averaging_time_spinner")
        self.gridLayout_5.addWidget(self.averaging_time_spinner, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 1, 1, 1)
        self.num_scans_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.num_scans_spinner.setMaximum(1000)
        self.num_scans_spinner.setProperty("value", 1)
        self.num_scans_spinner.setObjectName("num_scans_spinner")
        self.gridLayout_5.addWidget(self.num_scans_spinner, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(3)
        self.frame_6.setMidLineWidth(5)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout.addWidget(self.frame_6)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.variable_2_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.variable_2_combobox.setObjectName("variable_2_combobox")
        self.variable_2_combobox.addItem("")
        self.variable_2_combobox.setItemText(0, "")
        self.variable_2_combobox.addItem("")
        self.variable_2_combobox.addItem("")
        self.variable_2_combobox.addItem("")
        self.variable_2_combobox.addItem("")
        self.variable_2_combobox.addItem("")
        self.verticalLayout.addWidget(self.variable_2_combobox)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 2, 2, 1, 1)
        self.sweep_end_spinner_var_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sweep_end_spinner_var_2.setMinimum(-100000.0)
        self.sweep_end_spinner_var_2.setMaximum(100000.0)
        self.sweep_end_spinner_var_2.setObjectName("sweep_end_spinner_var_2")
        self.gridLayout_4.addWidget(self.sweep_end_spinner_var_2, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        self.sweep_start_spinner_var_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sweep_start_spinner_var_2.setObjectName("sweep_start_spinner_var_2")
        self.gridLayout_4.addWidget(self.sweep_start_spinner_var_2, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 1, 1, 1)
        self.num_steps_spinner_var_2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.num_steps_spinner_var_2.setMinimum(1)
        self.num_steps_spinner_var_2.setMaximum(100000)
        self.num_steps_spinner_var_2.setObjectName("num_steps_spinner_var_2")
        self.gridLayout_4.addWidget(self.num_steps_spinner_var_2, 3, 1, 1, 1)
        self.steps_display_var_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.steps_display_var_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.steps_display_var_2.setObjectName("steps_display_var_2")
        self.gridLayout_4.addWidget(self.steps_display_var_2, 0, 3, 4, 1)
        self.step_size_display_var_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.step_size_display_var_2.setEnabled(False)
        self.step_size_display_var_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.step_size_display_var_2.setObjectName("step_size_display_var_2")
        self.gridLayout_4.addWidget(self.step_size_display_var_2, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem8)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(3)
        self.frame_5.setMidLineWidth(5)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.notes_plain_text_edit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.notes_plain_text_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.notes_plain_text_edit.setObjectName("notes_plain_text_edit")
        self.verticalLayout.addWidget(self.notes_plain_text_edit)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem11)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setMidLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem13)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 8, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 9, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 6, 2, 1, 1)
        self.go_to_probe_wl_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_probe_wl_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_probe_wl_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_to_probe_wl_btn.setIcon(icon)
        self.go_to_probe_wl_btn.setObjectName("go_to_probe_wl_btn")
        self.gridLayout_2.addWidget(self.go_to_probe_wl_btn, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.static_field_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.static_field_spinner.setMaximum(100000.0)
        self.static_field_spinner.setObjectName("static_field_spinner")
        self.gridLayout_2.addWidget(self.static_field_spinner, 8, 0, 1, 1)
        self.go_to_static_field_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_static_field_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_static_field_btn.setText("")
        self.go_to_static_field_btn.setIcon(icon)
        self.go_to_static_field_btn.setObjectName("go_to_static_field_btn")
        self.gridLayout_2.addWidget(self.go_to_static_field_btn, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pump_mod_freq_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.pump_mod_freq_spinner.setDecimals(4)
        self.pump_mod_freq_spinner.setMaximum(250.0)
        self.pump_mod_freq_spinner.setObjectName("pump_mod_freq_spinner")
        self.gridLayout_2.addWidget(self.pump_mod_freq_spinner, 11, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.go_to_rf_mod_freq_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_rf_mod_freq_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_rf_mod_freq_btn.setText("")
        self.go_to_rf_mod_freq_btn.setIcon(icon)
        self.go_to_rf_mod_freq_btn.setObjectName("go_to_rf_mod_freq_btn")
        self.gridLayout_2.addWidget(self.go_to_rf_mod_freq_btn, 13, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 4, 2, 1, 1)
        self.go_to_rf_freq_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_rf_freq_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_rf_freq_btn.setText("")
        self.go_to_rf_freq_btn.setIcon(icon)
        self.go_to_rf_freq_btn.setObjectName("go_to_rf_freq_btn")
        self.gridLayout_2.addWidget(self.go_to_rf_freq_btn, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.temp_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.temp_spinner.setMaximum(500.0)
        self.temp_spinner.setObjectName("temp_spinner")
        self.gridLayout_2.addWidget(self.temp_spinner, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 12, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 13, 2, 1, 1)
        self.rf_freq_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.rf_freq_spinner.setDecimals(4)
        self.rf_freq_spinner.setMaximum(20.0)
        self.rf_freq_spinner.setObjectName("rf_freq_spinner")
        self.gridLayout_2.addWidget(self.rf_freq_spinner, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 11, 2, 1, 1)
        self.probe_wl_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.probe_wl_spinner.setMinimum(-10000.0)
        self.probe_wl_spinner.setMaximum(10000.0)
        self.probe_wl_spinner.setObjectName("probe_wl_spinner")
        self.gridLayout_2.addWidget(self.probe_wl_spinner, 4, 0, 1, 1)
        self.go_to_temp_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_temp_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_temp_btn.setText("")
        self.go_to_temp_btn.setIcon(icon)
        self.go_to_temp_btn.setObjectName("go_to_temp_btn")
        self.gridLayout_2.addWidget(self.go_to_temp_btn, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.go_to_pump_mod_freq_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.go_to_pump_mod_freq_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.go_to_pump_mod_freq_btn.setText("")
        self.go_to_pump_mod_freq_btn.setIcon(icon)
        self.go_to_pump_mod_freq_btn.setObjectName("go_to_pump_mod_freq_btn")
        self.gridLayout_2.addWidget(self.go_to_pump_mod_freq_btn, 11, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 0, 0, 1, 1)
        self.rf_mod_freq_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.rf_mod_freq_spinner.setDecimals(4)
        self.rf_mod_freq_spinner.setMaximum(250.0)
        self.rf_mod_freq_spinner.setObjectName("rf_mod_freq_spinner")
        self.gridLayout_2.addWidget(self.rf_mod_freq_spinner, 13, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.scroll_area_control_panel.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scroll_area_control_panel, 1, 0, 17, 1)
        self.PlotWidget = PlotWidget(self.centralwidget)
        self.PlotWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.PlotWidget.setObjectName("PlotWidget")
        self.gridLayout.addWidget(self.PlotWidget, 1, 2, 18, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(500, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 18, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1427, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInstruments = QtWidgets.QMenu(self.menubar)
        self.menuInstruments.setObjectName("menuInstruments")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.main_toolbar = QtWidgets.QToolBar(MainWindow)
        self.main_toolbar.setObjectName("main_toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.main_toolbar)
        self.actionMonochromator = QtWidgets.QAction(MainWindow)
        self.actionMonochromator.setObjectName("actionMonochromator")
        self.actionSR844_Lock_in_Amplifier = QtWidgets.QAction(MainWindow)
        self.actionSR844_Lock_in_Amplifier.setObjectName("actionSR844_Lock_in_Amplifier")
        self.actionCryostat_Magnet = QtWidgets.QAction(MainWindow)
        self.actionCryostat_Magnet.setObjectName("actionCryostat_Magnet")
        self.actionMicrowave_Source = QtWidgets.QAction(MainWindow)
        self.actionMicrowave_Source.setObjectName("actionMicrowave_Source")
        self.actionFunction_Generator_AOM_Driver = QtWidgets.QAction(MainWindow)
        self.actionFunction_Generator_AOM_Driver.setObjectName("actionFunction_Generator_AOM_Driver")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon1)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("help-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave_Current_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Current_Settings.setObjectName("actionSave_Current_Settings")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("download_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Data.setIcon(icon3)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionConnect_All = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("connect_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect_All.setIcon(icon4)
        self.actionConnect_All.setObjectName("actionConnect_All")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionSave_Current_Settings)
        self.menuFile.addAction(self.actionSave_Data)
        self.menuInstruments.addSeparator()
        self.menuInstruments.addAction(self.actionMonochromator)
        self.menuInstruments.addAction(self.actionSR844_Lock_in_Amplifier)
        self.menuInstruments.addAction(self.actionCryostat_Magnet)
        self.menuInstruments.addAction(self.actionMicrowave_Source)
        self.menuInstruments.addAction(self.actionFunction_Generator_AOM_Driver)
        self.menuInstruments.addAction(self.actionConnect_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstruments.menuAction())
        self.main_toolbar.addAction(self.actionSettings)
        self.main_toolbar.addAction(self.actionHelp)
        self.main_toolbar.addAction(self.actionSave_Data)
        self.main_toolbar.addAction(self.actionConnect_All)

        self.retranslateUi(MainWindow)
        self.actionMonochromator.triggered.connect(MainWindow.open_mono_window)
        self.actionSR844_Lock_in_Amplifier.triggered.connect(MainWindow.open_lockin_window)
        self.actionHelp.triggered.connect(MainWindow.open_help_window)
        self.start_btn.clicked.connect(MainWindow.start_btn_clicked)
        self.pause_btn.clicked.connect(MainWindow.pause_btn_clicked)
        self.stop_btn.clicked.connect(MainWindow.stop_btn_clicked)
        self.go_to_temp_btn.clicked.connect(MainWindow.go_to_temp_btn_clicked)
        self.go_to_probe_wl_btn.clicked.connect(MainWindow.go_to_probe_wl_btn_clicked)
        self.go_to_rf_freq_btn.clicked.connect(MainWindow.go_to_rf_freq_btn_clicked)
        self.go_to_static_field_btn.clicked.connect(MainWindow.go_to_static_field_btn_clicked)
        self.go_to_pump_mod_freq_btn.clicked.connect(MainWindow.go_to_pump_mod_freq_btn_clicked)
        self.go_to_rf_mod_freq_btn.clicked.connect(MainWindow.go_to_rf_mod_freq_btn_clicked)
        self.pushButton.clicked.connect(MainWindow.set_all_constants_btn_clicked)
        self.variable_1_combobox.currentIndexChanged['QString'].connect(MainWindow.primary_indep_var_combobox_activated)
        self.variable_2_combobox.currentIndexChanged['QString'].connect(MainWindow.secondary_indep_var_combobox_activated)
        self.experiment_presets_combobox.activated['QString'].connect(MainWindow.experiment_preset_combobox_activated)
        self.sweep_start_spinner.valueChanged['double'].connect(MainWindow.calc_steps_from_num)
        self.sweep_end_spinner.valueChanged['double'].connect(MainWindow.calc_steps_from_num)
        self.num_steps_spinner.valueChanged['int'].connect(MainWindow.calc_steps_from_num)
        self.autosave_checkbox.toggled['bool'].connect(MainWindow.autosave_checkbox_toggled)
        self.log_spacing_checkbox.toggled['bool'].connect(MainWindow.log_spacing_checkbox_toggled)
        self.actionSettings.triggered.connect(MainWindow.open_settings_window)
        self.actionSave_Data.triggered.connect(MainWindow.save_data)
        self.actionConnect_All.triggered.connect(MainWindow.connect_instruments)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PA-DMR Experiment Control"))
        self.autosave_checkbox.setText(_translate("MainWindow", "AutoSave Data"))
        self.label_14.setText(_translate("MainWindow", "Experiment Presets:"))
        self.experiment_presets_combobox.setItemText(0, _translate("MainWindow", "-Manual Setup-"))
        self.experiment_presets_combobox.setItemText(1, _translate("MainWindow", "Optical Absorption Spectrum"))
        self.experiment_presets_combobox.setItemText(2, _translate("MainWindow", "PL Lifetime"))
        self.experiment_presets_combobox.setItemText(3, _translate("MainWindow", "PA Lifetime (Single WL)"))
        self.experiment_presets_combobox.setItemText(4, _translate("MainWindow", "PA Spectrum (Single Phase)"))
        self.experiment_presets_combobox.setItemText(5, _translate("MainWindow", "PA Lifetime/Spectrum (xyz)"))
        self.experiment_presets_combobox.setItemText(6, _translate("MainWindow", "PL-DMR Magnetic Spectrum (Field-Swept)"))
        self.experiment_presets_combobox.setItemText(7, _translate("MainWindow", "PL-DMR Lifetime (Single Field)"))
        self.experiment_presets_combobox.setItemText(8, _translate("MainWindow", "PA-DMR Magnetic Spectrum (Field-Swept)"))
        self.experiment_presets_combobox.setItemText(9, _translate("MainWindow", "PA-DMR Optical Spectrum (Single Field)"))
        self.experiment_presets_combobox.setItemText(10, _translate("MainWindow", "PA-DMR RF Mod Freq Scan"))
        self.label_12.setText(_translate("MainWindow", "Primary Independent Variable (xy- data):"))
        self.variable_1_combobox.setItemText(1, _translate("MainWindow", "Pump Modulation Frequency"))
        self.variable_1_combobox.setItemText(2, _translate("MainWindow", "Probe Wavelength"))
        self.variable_1_combobox.setItemText(3, _translate("MainWindow", "Static Magnetic Field"))
        self.variable_1_combobox.setItemText(4, _translate("MainWindow", "RF Carrier Frequency"))
        self.variable_1_combobox.setItemText(5, _translate("MainWindow", "RF Modulation Frequency"))
        self.label_17.setText(_translate("MainWindow", "Number of Steps"))
        self.label_15.setText(_translate("MainWindow", "Sweep Start"))
        self.label_18.setText(_translate("MainWindow", "Step Size"))
        self.label_16.setText(_translate("MainWindow", "Sweep End"))
        self.log_spacing_checkbox.setText(_translate("MainWindow", "Log Spacing"))
        self.label_23.setText(_translate("MainWindow", "Scan Settings:"))
        self.label_24.setText(_translate("MainWindow", "Averaging Time (s)"))
        self.label_25.setText(_translate("MainWindow", "Number of Scans"))
        self.label_5.setText(_translate("MainWindow", "Secondary Independent Variable (xyz- data only):"))
        self.variable_2_combobox.setItemText(1, _translate("MainWindow", "Pump Modulation Frequency"))
        self.variable_2_combobox.setItemText(2, _translate("MainWindow", "Probe Wavelength"))
        self.variable_2_combobox.setItemText(3, _translate("MainWindow", "Static Magnetic Field"))
        self.variable_2_combobox.setItemText(4, _translate("MainWindow", "RF Carrier Frequency"))
        self.variable_2_combobox.setItemText(5, _translate("MainWindow", "RF Modulation Frequency"))
        self.label_22.setText(_translate("MainWindow", "Step Size"))
        self.label_20.setText(_translate("MainWindow", "Sweep End"))
        self.label_21.setText(_translate("MainWindow", "Number of Steps"))
        self.label_19.setText(_translate("MainWindow", "Sweep Start"))
        self.label_10.setText(_translate("MainWindow", "Notes:"))
        self.label_6.setText(_translate("MainWindow", "Constants"))
        self.label_2.setText(_translate("MainWindow", "Temperature (K)"))
        self.label_8.setText(_translate("MainWindow", "Pump Modulation Frequency (MHz)"))
        self.label_7.setText(_translate("MainWindow", "Probe Wavelength (nm)"))
        self.pushButton.setText(_translate("MainWindow", "Set All"))
        self.label_9.setText(_translate("MainWindow", "Static Magnetic Field (Gauss)"))
        self.label_13.setText(_translate("MainWindow", "Actual"))
        self.label_4.setText(_translate("MainWindow", "RF Modulation Frequency (MHz)"))
        self.label_3.setText(_translate("MainWindow", "RF Frequency (GHz)"))
        self.label_31.setText(_translate("MainWindow", "Setpoint"))
        self.label.setText(_translate("MainWindow", "Plot"))
        self.label_11.setText(_translate("MainWindow", "Experiment Setup"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuInstruments.setTitle(_translate("MainWindow", "Instruments"))
        self.main_toolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionMonochromator.setText(_translate("MainWindow", "Monochromator"))
        self.actionSR844_Lock_in_Amplifier.setText(_translate("MainWindow", "SR844 (Lock-in Amplifier)"))
        self.actionCryostat_Magnet.setText(_translate("MainWindow", "Cryostat/Magnet"))
        self.actionMicrowave_Source.setText(_translate("MainWindow", "Microwave Source"))
        self.actionFunction_Generator_AOM_Driver.setText(_translate("MainWindow", "Function Generator (AOM Driver)"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionSave_Current_Settings.setText(_translate("MainWindow", "Save Current Settings"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Stored Data as"))
        self.actionSave_Data.setToolTip(_translate("MainWindow", "Save data to file"))
        self.actionSave_Data.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionConnect_All.setText(_translate("MainWindow", "Initialize Selected Instruments (see Settings)"))
from plotwidget import PlotWidget
