# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ryan/AppData/Local/Temp/settings_widget_UIyZJpPh.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(608, 766)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.set_all_params_btn = QtWidgets.QPushButton(Form)
        self.set_all_params_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.set_all_params_btn.setObjectName("set_all_params_btn")
        self.gridLayout_3.addWidget(self.set_all_params_btn, 2, 1, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(Form)
        self.cancel_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_3.addWidget(self.cancel_btn, 2, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 1, 1, 1)
        self.set_tab_params_btn = QtWidgets.QPushButton(Form)
        self.set_tab_params_btn.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.set_tab_params_btn.setObjectName("set_tab_params_btn")
        self.gridLayout_3.addWidget(self.set_tab_params_btn, 2, 0, 1, 1)
        self.tab_widget = QtWidgets.QTabWidget(Form)
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.general_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.general_tab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 535, 702))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 8, 0, 1, 1)
        self.status_ind_sr844 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_sr844.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_sr844.setObjectName("status_ind_sr844")
        self.gridLayout_8.addWidget(self.status_ind_sr844, 3, 2, 1, 1)
        self.toptica_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.toptica_com_port_spinner.setObjectName("toptica_com_port_spinner")
        self.gridLayout_8.addWidget(self.toptica_com_port_spinner, 23, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 16, 0, 1, 1)
        self.toptica_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.toptica_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toptica_checkbox.setText("")
        self.toptica_checkbox.setObjectName("toptica_checkbox")
        self.gridLayout_8.addWidget(self.toptica_checkbox, 10, 1, 1, 1)
        self.cg635_gpib_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.cg635_gpib_spinner.setObjectName("cg635_gpib_spinner")
        self.gridLayout_8.addWidget(self.cg635_gpib_spinner, 17, 2, 1, 1)
        self.sr830_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.sr830_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sr830_checkbox.setText("")
        self.sr830_checkbox.setObjectName("sr830_checkbox")
        self.gridLayout_8.addWidget(self.sr830_checkbox, 4, 1, 1, 1)
        self.cg635_com_port = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.cg635_com_port.setObjectName("cg635_com_port")
        self.gridLayout_8.addWidget(self.cg635_com_port, 20, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 17, 0, 1, 1)
        self.status_ind_sr830 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_sr830.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_sr830.setObjectName("status_ind_sr830")
        self.gridLayout_8.addWidget(self.status_ind_sr830, 4, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(3)
        self.frame_5.setMidLineWidth(5)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8.addWidget(self.frame_5, 11, 0, 1, 3)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 7, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 1, 1, 1, 1)
        self.status_ind_smb100a = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_smb100a.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_smb100a.setObjectName("status_ind_smb100a")
        self.gridLayout_8.addWidget(self.status_ind_smb100a, 8, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 9, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 18, 0, 1, 1)
        self.smb100a_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.smb100a_com_port_spinner.setObjectName("smb100a_com_port_spinner")
        self.gridLayout_8.addWidget(self.smb100a_com_port_spinner, 21, 2, 1, 1)
        self.montana_instr_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.montana_instr_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.montana_instr_checkbox.setText("")
        self.montana_instr_checkbox.setObjectName("montana_instr_checkbox")
        self.gridLayout_8.addWidget(self.montana_instr_checkbox, 9, 1, 1, 1)
        self.prologix_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.prologix_com_port_spinner.setObjectName("prologix_com_port_spinner")
        self.gridLayout_8.addWidget(self.prologix_com_port_spinner, 18, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(3)
        self.frame_4.setMidLineWidth(5)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8.addWidget(self.frame_4, 5, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 15, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 21, 0, 1, 1)
        self.cg635_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.cg635_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cg635_checkbox.setText("")
        self.cg635_checkbox.setObjectName("cg635_checkbox")
        self.gridLayout_8.addWidget(self.cg635_checkbox, 7, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 3, 0, 1, 1)
        self.status_ind_cryostat = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_cryostat.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_cryostat.setObjectName("status_ind_cryostat")
        self.gridLayout_8.addWidget(self.status_ind_cryostat, 9, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 22, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setMidLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8.addWidget(self.frame_3, 2, 0, 1, 3)
        self.sr830_gpib_address_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.sr830_gpib_address_spinner.setObjectName("sr830_gpib_address_spinner")
        self.gridLayout_8.addWidget(self.sr830_gpib_address_spinner, 16, 2, 1, 1)
        self.md2000_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.md2000_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.md2000_checkbox.setText("")
        self.md2000_checkbox.setObjectName("md2000_checkbox")
        self.gridLayout_8.addWidget(self.md2000_checkbox, 6, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 4, 0, 1, 1)
        self.sr844_gpib_address_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.sr844_gpib_address_spinner.setObjectName("sr844_gpib_address_spinner")
        self.gridLayout_8.addWidget(self.sr844_gpib_address_spinner, 15, 2, 1, 1)
        self.mono_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.mono_com_port_spinner.setObjectName("mono_com_port_spinner")
        self.gridLayout_8.addWidget(self.mono_com_port_spinner, 19, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 13, 0, 1, 1)
        self.status_ind_md2000 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_md2000.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_md2000.setObjectName("status_ind_md2000")
        self.gridLayout_8.addWidget(self.status_ind_md2000, 6, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 12, 0, 1, 3)
        self.cryostat_com_port_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.cryostat_com_port_spinner.setObjectName("cryostat_com_port_spinner")
        self.gridLayout_8.addWidget(self.cryostat_com_port_spinner, 22, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 19, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 23, 0, 1, 1)
        self.status_ind_toptica = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_toptica.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_toptica.setObjectName("status_ind_toptica")
        self.gridLayout_8.addWidget(self.status_ind_toptica, 10, 2, 1, 1)
        self.smb100a_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.smb100a_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.smb100a_checkbox.setText("")
        self.smb100a_checkbox.setObjectName("smb100a_checkbox")
        self.gridLayout_8.addWidget(self.smb100a_checkbox, 8, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 20, 0, 1, 1)
        self.status_ind_cg635 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.status_ind_cg635.setAlignment(QtCore.Qt.AlignCenter)
        self.status_ind_cg635.setObjectName("status_ind_cg635")
        self.gridLayout_8.addWidget(self.status_ind_cg635, 7, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 10, 0, 1, 1)
        self.sr844_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.sr844_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sr844_checkbox.setText("")
        self.sr844_checkbox.setObjectName("sr844_checkbox")
        self.gridLayout_8.addWidget(self.sr844_checkbox, 3, 1, 1, 1)
        self.cg635_comm_format_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.cg635_comm_format_combobox.setObjectName("cg635_comm_format_combobox")
        self.cg635_comm_format_combobox.addItem("")
        self.cg635_comm_format_combobox.addItem("")
        self.gridLayout_8.addWidget(self.cg635_comm_format_combobox, 13, 2, 1, 1)
        self.connect_instr_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connect_instr_btn.setFont(font)
        self.connect_instr_btn.setWhatsThis("")
        self.connect_instr_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("connect_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connect_instr_btn.setIcon(icon1)
        self.connect_instr_btn.setIconSize(QtCore.QSize(30, 30))
        self.connect_instr_btn.setObjectName("connect_instr_btn")
        self.gridLayout_8.addWidget(self.connect_instr_btn, 0, 0, 1, 3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tab_widget.addTab(self.general_tab, "")
        self.lockin_tab = QtWidgets.QWidget()
        self.lockin_tab.setObjectName("lockin_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.lockin_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.lockin_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 556, 625))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 22, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 17, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.input_impedance_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.input_impedance_combobox.setObjectName("input_impedance_combobox")
        self.input_impedance_combobox.addItem("")
        self.input_impedance_combobox.addItem("")
        self.gridLayout.addWidget(self.input_impedance_combobox, 14, 1, 1, 1)
        self.close_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.close_reserve_combobox.setObjectName("close_reserve_combobox")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.close_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.close_reserve_combobox, 11, 1, 1, 1)
        self.outputs_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.outputs_combobox.setObjectName("outputs_combobox")
        self.outputs_combobox.addItem("")
        self.outputs_combobox.addItem("")
        self.outputs_combobox.addItem("")
        self.gridLayout.addWidget(self.outputs_combobox, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.filter_slope_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.filter_slope_combobox.setObjectName("filter_slope_combobox")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.filter_slope_combobox.addItem("")
        self.gridLayout.addWidget(self.filter_slope_combobox, 8, 1, 1, 1)
        self.ref_source_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.ref_source_combobox.setObjectName("ref_source_combobox")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.ref_source_combobox.addItem("")
        self.gridLayout.addWidget(self.ref_source_combobox, 16, 1, 1, 1)
        self.wide_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.wide_reserve_combobox.setObjectName("wide_reserve_combobox")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.wide_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.wide_reserve_combobox, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.expand_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.expand_combobox.setObjectName("expand_combobox")
        self.expand_combobox.addItem("")
        self.expand_combobox.addItem("")
        self.expand_combobox.addItem("")
        self.gridLayout.addWidget(self.expand_combobox, 20, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 18, 0, 1, 1)
        self.time_constant_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.time_constant_combobox.setObjectName("time_constant_combobox")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.time_constant_combobox.addItem("")
        self.gridLayout.addWidget(self.time_constant_combobox, 9, 1, 1, 1)
        self.phase_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.phase_spinner.setObjectName("phase_spinner")
        self.gridLayout.addWidget(self.phase_spinner, 19, 1, 1, 1)
        self.auto_creserve_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.auto_creserve_btn.setObjectName("auto_creserve_btn")
        self.gridLayout.addWidget(self.auto_creserve_btn, 11, 2, 1, 1)
        self.auto_dyn_reserve_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.auto_dyn_reserve_btn.setObjectName("auto_dyn_reserve_btn")
        self.gridLayout.addWidget(self.auto_dyn_reserve_btn, 12, 2, 1, 1)
        self.harmonic_spinner = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.harmonic_spinner.setObjectName("harmonic_spinner")
        self.gridLayout.addWidget(self.harmonic_spinner, 18, 1, 1, 1)
        self.sr844_harmonic_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sr844_harmonic_combobox.setObjectName("sr844_harmonic_combobox")
        self.sr844_harmonic_combobox.addItem("")
        self.sr844_harmonic_combobox.addItem("")
        self.gridLayout.addWidget(self.sr844_harmonic_combobox, 17, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 19, 2, 1, 1)
        self.dynamic_reserve_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.dynamic_reserve_combobox.setObjectName("dynamic_reserve_combobox")
        self.dynamic_reserve_combobox.addItem("")
        self.dynamic_reserve_combobox.addItem("")
        self.dynamic_reserve_combobox.addItem("")
        self.gridLayout.addWidget(self.dynamic_reserve_combobox, 12, 1, 1, 1)
        self.ref_impedance_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.ref_impedance_combobox.setObjectName("ref_impedance_combobox")
        self.ref_impedance_combobox.addItem("")
        self.ref_impedance_combobox.addItem("")
        self.gridLayout.addWidget(self.ref_impedance_combobox, 15, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 15, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 19, 0, 1, 1)
        self.auto_wreserve_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.auto_wreserve_btn.setObjectName("auto_wreserve_btn")
        self.gridLayout.addWidget(self.auto_wreserve_btn, 10, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.save_as_dflt_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.save_as_dflt_btn.setObjectName("save_as_dflt_btn")
        self.gridLayout.addWidget(self.save_as_dflt_btn, 21, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 14, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.sampling_rate_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sampling_rate_combobox.setObjectName("sampling_rate_combobox")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.sampling_rate_combobox.addItem("")
        self.gridLayout.addWidget(self.sampling_rate_combobox, 13, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 20, 0, 1, 1)
        self.sensitivity_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.sensitivity_combobox.setObjectName("sensitivity_combobox")
        self.sensitivity_combobox.addItem("")
        self.gridLayout.addWidget(self.sensitivity_combobox, 6, 1, 1, 1)
        self.auto_sens_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.auto_sens_btn.setObjectName("auto_sens_btn")
        self.gridLayout.addWidget(self.auto_sens_btn, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 16, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 2, 1, 1)
        self.lockin_model_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lockin_model_lineedit.setReadOnly(True)
        self.lockin_model_lineedit.setObjectName("lockin_model_lineedit")
        self.gridLayout.addWidget(self.lockin_model_lineedit, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tab_widget.addTab(self.lockin_tab, "")
        self.mono_tab = QtWidgets.QWidget()
        self.mono_tab.setObjectName("mono_tab")
        self.tab_widget.addTab(self.mono_tab, "")
        self.rns_tab = QtWidgets.QWidget()
        self.rns_tab.setObjectName("rns_tab")
        self.tab_widget.addTab(self.rns_tab, "")
        self.cg635_tab = QtWidgets.QWidget()
        self.cg635_tab.setObjectName("cg635_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cg635_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.cg635_tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 556, 625))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cg635_write_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_write_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cg635_write_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cg635_write_btn.setIcon(icon2)
        self.cg635_write_btn.setObjectName("cg635_write_btn")
        self.gridLayout_6.addWidget(self.cg635_write_btn, 17, 3, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setMaximum(2050.0)
        self.doubleSpinBox.setProperty("value", 250.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_6.addWidget(self.doubleSpinBox, 8, 1, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setMidLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6.addWidget(self.frame_2, 7, 0, 1, 4)
        self.cg635_set_freq_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.cg635_set_freq_spinner.setDecimals(16)
        self.cg635_set_freq_spinner.setMinimum(0.0)
        self.cg635_set_freq_spinner.setMaximum(2050000000.0)
        self.cg635_set_freq_spinner.setObjectName("cg635_set_freq_spinner")
        self.gridLayout_6.addWidget(self.cg635_set_freq_spinner, 3, 1, 1, 1)
        self.cg635_response_textedit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.cg635_response_textedit.setObjectName("cg635_response_textedit")
        self.gridLayout_6.addWidget(self.cg635_response_textedit, 18, 0, 1, 4)
        self.cg635_set_phase_spinner = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.cg635_set_phase_spinner.setDecimals(10)
        self.cg635_set_phase_spinner.setMinimum(-360.0)
        self.cg635_set_phase_spinner.setMaximum(360.0)
        self.cg635_set_phase_spinner.setObjectName("cg635_set_phase_spinner")
        self.gridLayout_6.addWidget(self.cg635_set_phase_spinner, 4, 1, 1, 2)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 4, 0, 1, 1)
        self.cg635_set_freq_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_set_freq_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cg635_set_freq_btn.setText("")
        self.cg635_set_freq_btn.setIcon(icon2)
        self.cg635_set_freq_btn.setObjectName("cg635_set_freq_btn")
        self.gridLayout_6.addWidget(self.cg635_set_freq_btn, 3, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 14, 0, 1, 4)
        self.cg635_set_phase_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_set_phase_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cg635_set_phase_btn.setText("")
        self.cg635_set_phase_btn.setIcon(icon2)
        self.cg635_set_phase_btn.setObjectName("cg635_set_phase_btn")
        self.gridLayout_6.addWidget(self.cg635_set_phase_btn, 4, 3, 1, 1)
        self.cg635_write_cmd_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cg635_write_cmd_lineedit.setObjectName("cg635_write_cmd_lineedit")
        self.gridLayout_6.addWidget(self.cg635_write_cmd_lineedit, 17, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 6, 0, 1, 1)
        self.cg635_write_btn_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_write_btn_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cg635_write_btn_2.setText("")
        self.cg635_write_btn_2.setIcon(icon2)
        self.cg635_write_btn_2.setObjectName("cg635_write_btn_2")
        self.gridLayout_6.addWidget(self.cg635_write_btn_2, 8, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 0, 0, 1, 4)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(3)
        self.frame_6.setMidLineWidth(5)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6.addWidget(self.frame_6, 12, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 13, 0, 1, 4)
        self.cg635_set_current_phase_zero_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_set_current_phase_zero_btn.setObjectName("cg635_set_current_phase_zero_btn")
        self.gridLayout_6.addWidget(self.cg635_set_current_phase_zero_btn, 5, 0, 1, 4)
        self.cg635_freq_units_combobox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cg635_freq_units_combobox.setObjectName("cg635_freq_units_combobox")
        self.cg635_freq_units_combobox.addItem("")
        self.cg635_freq_units_combobox.addItem("")
        self.cg635_freq_units_combobox.addItem("")
        self.cg635_freq_units_combobox.addItem("")
        self.gridLayout_6.addWidget(self.cg635_freq_units_combobox, 3, 2, 1, 1)
        self.cg635_run_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_run_btn.setObjectName("cg635_run_btn")
        self.gridLayout_6.addWidget(self.cg635_run_btn, 2, 0, 1, 2)
        self.cg635_check_errors_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_check_errors_btn.setObjectName("cg635_check_errors_btn")
        self.gridLayout_6.addWidget(self.cg635_check_errors_btn, 17, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 16, 1, 1, 2)
        self.cg635_stop_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cg635_stop_btn.setObjectName("cg635_stop_btn")
        self.gridLayout_6.addWidget(self.cg635_stop_btn, 2, 2, 1, 2)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 8, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tab_widget.addTab(self.cg635_tab, "")
        self.cryostat_tab = QtWidgets.QWidget()
        self.cryostat_tab.setObjectName("cryostat_tab")
        self.tab_widget.addTab(self.cryostat_tab, "")
        self.laser_tab = QtWidgets.QWidget()
        self.laser_tab.setObjectName("laser_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.laser_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_48 = QtWidgets.QLabel(self.laser_tab)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 8, 0, 1, 1)
        self.toptica_emission_indicator = QtWidgets.QLabel(self.laser_tab)
        self.toptica_emission_indicator.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toptica_emission_indicator.setFont(font)
        self.toptica_emission_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.toptica_emission_indicator.setObjectName("toptica_emission_indicator")
        self.gridLayout_4.addWidget(self.toptica_emission_indicator, 1, 0, 1, 5)
        self.toptica_temp_stable_indicator = QtWidgets.QLabel(self.laser_tab)
        self.toptica_temp_stable_indicator.setMaximumSize(QtCore.QSize(16777215, 60))
        self.toptica_temp_stable_indicator.setObjectName("toptica_temp_stable_indicator")
        self.gridLayout_4.addWidget(self.toptica_temp_stable_indicator, 2, 0, 1, 5)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.laser_tab)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 8, 2, 1, 1)
        self.toptica_set_power_btn = QtWidgets.QPushButton(self.laser_tab)
        self.toptica_set_power_btn.setText("")
        self.toptica_set_power_btn.setIcon(icon2)
        self.toptica_set_power_btn.setObjectName("toptica_set_power_btn")
        self.gridLayout_4.addWidget(self.toptica_set_power_btn, 7, 4, 1, 1)
        self.toptica_bias_units_combobox = QtWidgets.QComboBox(self.laser_tab)
        self.toptica_bias_units_combobox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.toptica_bias_units_combobox.setObjectName("toptica_bias_units_combobox")
        self.toptica_bias_units_combobox.addItem("")
        self.toptica_bias_units_combobox.addItem("")
        self.gridLayout_4.addWidget(self.toptica_bias_units_combobox, 8, 3, 1, 1)
        self.toptica_set_bias_power_btn = QtWidgets.QPushButton(self.laser_tab)
        self.toptica_set_bias_power_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.toptica_set_bias_power_btn.setText("")
        self.toptica_set_bias_power_btn.setIcon(icon2)
        self.toptica_set_bias_power_btn.setObjectName("toptica_set_bias_power_btn")
        self.gridLayout_4.addWidget(self.toptica_set_bias_power_btn, 8, 4, 1, 1)
        self.toptica_enable_digital_input_btn = QtWidgets.QPushButton(self.laser_tab)
        self.toptica_enable_digital_input_btn.setObjectName("toptica_enable_digital_input_btn")
        self.gridLayout_4.addWidget(self.toptica_enable_digital_input_btn, 6, 0, 1, 5)
        self.toptica_units_combobox = QtWidgets.QComboBox(self.laser_tab)
        self.toptica_units_combobox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.toptica_units_combobox.setObjectName("toptica_units_combobox")
        self.toptica_units_combobox.addItem("")
        self.toptica_units_combobox.addItem("")
        self.gridLayout_4.addWidget(self.toptica_units_combobox, 7, 3, 1, 1)
        self.toptica_power_spinner = QtWidgets.QDoubleSpinBox(self.laser_tab)
        self.toptica_power_spinner.setObjectName("toptica_power_spinner")
        self.gridLayout_4.addWidget(self.toptica_power_spinner, 7, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.laser_tab)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_46 = QtWidgets.QLabel(self.laser_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_2.addWidget(self.label_46)
        self.pushButton_3 = QtWidgets.QPushButton(self.laser_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.toptica_start_laser_btn = QtWidgets.QPushButton(self.laser_tab)
        self.toptica_start_laser_btn.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toptica_start_laser_btn.setFont(font)
        self.toptica_start_laser_btn.setObjectName("toptica_start_laser_btn")
        self.verticalLayout_2.addWidget(self.toptica_start_laser_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.toptica_stop_laser_btn = QtWidgets.QPushButton(self.laser_tab)
        self.toptica_stop_laser_btn.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toptica_stop_laser_btn.setFont(font)
        self.toptica_stop_laser_btn.setObjectName("toptica_stop_laser_btn")
        self.horizontalLayout.addWidget(self.toptica_stop_laser_btn)
        self.gridLayout_4.addLayout(self.horizontalLayout, 5, 0, 1, 5)
        self.tab_widget.addTab(self.laser_tab, "")
        self.gridLayout_3.addWidget(self.tab_widget, 0, 0, 1, 3)

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(6)
        self.set_all_params_btn.clicked.connect(Form.set_all_params_btn_clicked)
        self.cancel_btn.clicked.connect(Form.cancel_btn_clicked)
        self.set_tab_params_btn.clicked.connect(Form.set_tab_params_btn_clicked)
        self.save_as_dflt_btn.clicked.connect(Form.save_as_dflt_btn_clicked)
        self.auto_sens_btn.clicked.connect(Form.auto_sens_btn_clicked)
        self.cg635_set_current_phase_zero_btn.clicked.connect(Form.cg635_define_phase_as_zero_btn_clicked)
        self.cg635_check_errors_btn.clicked.connect(Form.cg635_check_for_errors_btn_clicked)
        self.cg635_write_btn.clicked.connect(Form.cg635_write_manual_cmd_btn_clicked)
        self.cg635_freq_units_combobox.currentIndexChanged['int'].connect(Form.cg635_freq_units_changed)
        self.sr844_checkbox.clicked['bool'].connect(Form.sr844_checkbox_clicked)
        self.sr830_checkbox.clicked['bool'].connect(Form.sr830_checkbox_clicked)
        self.cg635_set_freq_btn.clicked.connect(Form.cg635_set_freq_btn_clicked)
        self.cg635_set_phase_btn.clicked.connect(Form.cg635_set_phase_btn_clicked)
        self.connect_instr_btn.clicked.connect(Form.connect_instr_btn_clicked)
        self.toptica_start_laser_btn.clicked.connect(Form.toptica_start_btn_clicked)
        self.toptica_stop_laser_btn.clicked.connect(Form.toptica_stop_btn_clicked)
        self.toptica_enable_digital_input_btn.clicked.connect(Form.toptica_ext_en_btn_clicked)
        self.toptica_set_power_btn.clicked.connect(Form.toptica_set_main_power_btn_clicked)
        self.toptica_set_bias_power_btn.clicked.connect(Form.toptica_set_bias_power_btn_clicked)
        self.pushButton_3.clicked.connect(Form.toptica_bias_enable_btn_clicked)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.set_all_params_btn.setText(_translate("Form", "All Tabs"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))
        self.label_29.setText(_translate("Form", "Set Parameters"))
        self.set_tab_params_btn.setText(_translate("Form", "Current Tab"))
        self.label_26.setText(_translate("Form", "RF (Microwave) Source (SMB100A)"))
        self.status_ind_sr844.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.label_16.setText(_translate("Form", "SR830 (GPIB Address)"))
        self.label_30.setText(_translate("Form", "CG635 (GPIB Address)"))
        self.status_ind_sr830.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/GREEN_LED_ON.png\"/></p></body></html>"))
        self.label_25.setText(_translate("Form", "Clock Generator (CG 635)"))
        self.label_37.setText(_translate("Form", "Use?"))
        self.status_ind_smb100a.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.label_27.setText(_translate("Form", "Cryostat/Magnet (Montana Instruments)"))
        self.label_40.setText(_translate("Form", "Prologix (Com Port)"))
        self.label_14.setText(_translate("Form", "SR844 (GPIB Address)"))
        self.label_24.setText(_translate("Form", "Monochromator Driver (MD2000)"))
        self.label_41.setText(_translate("Form", "SMB100A (Com Port)"))
        self.label_22.setText(_translate("Form", "SR844 Lock-in Amplifier (25-200 MHz)"))
        self.status_ind_cryostat.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.label_42.setText(_translate("Form", "Cryostat/Magnet (Com Port)"))
        self.label_38.setText(_translate("Form", "Connection Status"))
        self.label_21.setText(_translate("Form", "Available Instruments"))
        self.label_23.setText(_translate("Form", "SR830 Lock-in Amplifier (1 mHz - 102 kHz) "))
        self.label_31.setText(_translate("Form", "CG635 Communication Via:"))
        self.status_ind_md2000.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_ON.png\"/></p></body></html>"))
        self.label_39.setText(_translate("Form", "Communication Settings"))
        self.label_13.setText(_translate("Form", "Mono (Com Port)"))
        self.label_45.setText(_translate("Form", "Laser (Com Port)"))
        self.status_ind_toptica.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.label_44.setText(_translate("Form", "CG635 (Com Port; disregard if GPIB)"))
        self.status_ind_cg635.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.label_28.setText(_translate("Form", "Pump Laser (Toptica iBeam Smart)"))
        self.cg635_comm_format_combobox.setItemText(0, _translate("Form", "GPIB"))
        self.cg635_comm_format_combobox.setItemText(1, _translate("Form", "RS-232 via USB"))
        self.connect_instr_btn.setText(_translate("Form", "Connect"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("Form", "General"))
        self.label_12.setText(_translate("Form", "Note: Sensitivity default cannot be changed (damage risk)"))
        self.label_19.setText(_translate("Form", "2F Detect Mode (SR844)"))
        self.label_3.setText(_translate("Form", "Sensitivity"))
        self.input_impedance_combobox.setItemText(0, _translate("Form", "50 Ω"))
        self.input_impedance_combobox.setItemText(1, _translate("Form", "1 MΩ / 30 pF"))
        self.close_reserve_combobox.setItemText(0, _translate("Form", "High"))
        self.close_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.close_reserve_combobox.setItemText(2, _translate("Form", "Low Noise"))
        self.close_reserve_combobox.setItemText(3, _translate("Form", "Auto"))
        self.outputs_combobox.setItemText(0, _translate("Form", "R / θ (V/degrees)"))
        self.outputs_combobox.setItemText(1, _translate("Form", "X / Y"))
        self.outputs_combobox.setItemText(2, _translate("Form", "Manual"))
        self.label_15.setText(_translate("Form", "Filter Slope"))
        self.filter_slope_combobox.setItemText(0, _translate("Form", "No Filter"))
        self.filter_slope_combobox.setItemText(1, _translate("Form", "6 dB/Octave"))
        self.filter_slope_combobox.setItemText(2, _translate("Form", "12 dB/Octave"))
        self.filter_slope_combobox.setItemText(3, _translate("Form", "18 dB/Octave"))
        self.filter_slope_combobox.setItemText(4, _translate("Form", "24 dB/Octave"))
        self.ref_source_combobox.setItemText(0, _translate("Form", "External"))
        self.ref_source_combobox.setItemText(1, _translate("Form", "Internal"))
        self.ref_source_combobox.setItemText(2, _translate("Form", "2F (External Ref)"))
        self.ref_source_combobox.setItemText(3, _translate("Form", "2F (Internal Ref)"))
        self.wide_reserve_combobox.setItemText(0, _translate("Form", "High"))
        self.wide_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.wide_reserve_combobox.setItemText(2, _translate("Form", "Low Noise"))
        self.wide_reserve_combobox.setItemText(3, _translate("Form", "Auto"))
        self.label_2.setText(_translate("Form", "Outputs"))
        self.expand_combobox.setItemText(0, _translate("Form", "x1 (off)"))
        self.expand_combobox.setItemText(1, _translate("Form", "x10"))
        self.expand_combobox.setItemText(2, _translate("Form", "x100"))
        self.label_5.setText(_translate("Form", "Sampling Rate"))
        self.label_20.setText(_translate("Form", "Harmonic (SR830)"))
        self.time_constant_combobox.setItemText(0, _translate("Form", "100  μs"))
        self.time_constant_combobox.setItemText(1, _translate("Form", "300  μs"))
        self.time_constant_combobox.setItemText(2, _translate("Form", "1     ms"))
        self.time_constant_combobox.setItemText(3, _translate("Form", "3     ms"))
        self.time_constant_combobox.setItemText(4, _translate("Form", "10   ms"))
        self.time_constant_combobox.setItemText(5, _translate("Form", "30   ms"))
        self.time_constant_combobox.setItemText(6, _translate("Form", "100 ms"))
        self.time_constant_combobox.setItemText(7, _translate("Form", "300 ms"))
        self.time_constant_combobox.setItemText(8, _translate("Form", "1        s"))
        self.time_constant_combobox.setItemText(9, _translate("Form", "3        s"))
        self.time_constant_combobox.setItemText(10, _translate("Form", "10      s"))
        self.time_constant_combobox.setItemText(11, _translate("Form", "30      s"))
        self.time_constant_combobox.setItemText(12, _translate("Form", "100    s"))
        self.time_constant_combobox.setItemText(13, _translate("Form", "300    s"))
        self.time_constant_combobox.setItemText(14, _translate("Form", "1      ks"))
        self.time_constant_combobox.setItemText(15, _translate("Form", "3      ks"))
        self.time_constant_combobox.setItemText(16, _translate("Form", "10    ks"))
        self.time_constant_combobox.setItemText(17, _translate("Form", "30    ks"))
        self.auto_creserve_btn.setText(_translate("Form", "Auto"))
        self.auto_dyn_reserve_btn.setText(_translate("Form", "Auto"))
        self.sr844_harmonic_combobox.setItemText(0, _translate("Form", "Off"))
        self.sr844_harmonic_combobox.setItemText(1, _translate("Form", "On"))
        self.pushButton.setText(_translate("Form", "Auto Phase"))
        self.dynamic_reserve_combobox.setItemText(0, _translate("Form", "High Reserve (Max)"))
        self.dynamic_reserve_combobox.setItemText(1, _translate("Form", "Normal"))
        self.dynamic_reserve_combobox.setItemText(2, _translate("Form", "Low Noise (Min)"))
        self.ref_impedance_combobox.setItemText(0, _translate("Form", "50 Ω"))
        self.ref_impedance_combobox.setItemText(1, _translate("Form", "10 kΩ / 40 pF"))
        self.label_18.setText(_translate("Form", "Dynamic Reserve (SR830)"))
        self.label_9.setText(_translate("Form", "Reference Impedance"))
        self.label_11.setText(_translate("Form", "Phase"))
        self.auto_wreserve_btn.setText(_translate("Form", "Auto"))
        self.label_7.setText(_translate("Form", "Close Reserve (SR844)"))
        self.save_as_dflt_btn.setText(_translate("Form", "Save as Default Values"))
        self.label.setText(_translate("Form", "Wide Reserve (SR844)"))
        self.label_4.setText(_translate("Form", "Time Constant"))
        self.label_6.setText(_translate("Form", "Input Impedance"))
        self.label_17.setText(_translate("Form", "Lock-in Model"))
        self.sampling_rate_combobox.setItemText(0, _translate("Form", "0.0625 (16 s)"))
        self.sampling_rate_combobox.setItemText(1, _translate("Form", "0.125 (8 s)"))
        self.sampling_rate_combobox.setItemText(2, _translate("Form", "0.250 (4 s)"))
        self.sampling_rate_combobox.setItemText(3, _translate("Form", "0.500 (2 s)"))
        self.sampling_rate_combobox.setItemText(4, _translate("Form", "1"))
        self.sampling_rate_combobox.setItemText(5, _translate("Form", "2"))
        self.sampling_rate_combobox.setItemText(6, _translate("Form", "4"))
        self.sampling_rate_combobox.setItemText(7, _translate("Form", "8"))
        self.sampling_rate_combobox.setItemText(8, _translate("Form", "16"))
        self.sampling_rate_combobox.setItemText(9, _translate("Form", "32"))
        self.sampling_rate_combobox.setItemText(10, _translate("Form", "64"))
        self.sampling_rate_combobox.setItemText(11, _translate("Form", "128"))
        self.sampling_rate_combobox.setItemText(12, _translate("Form", "256"))
        self.sampling_rate_combobox.setItemText(13, _translate("Form", "512"))
        self.sampling_rate_combobox.setItemText(14, _translate("Form", "Trigger"))
        self.label_8.setText(_translate("Form", "Expand"))
        self.sensitivity_combobox.setItemText(0, _translate("Form", "UNDER CONSTRUCTION"))
        self.auto_sens_btn.setText(_translate("Form", "Auto"))
        self.label_10.setText(_translate("Form", "Reference Source"))
        self.pushButton_2.setText(_translate("Form", "Auto Offset X/Y"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.lockin_tab), _translate("Form", "Lock-in"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.mono_tab), _translate("Form", "Mono"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.rns_tab), _translate("Form", "R&&S"))
        self.label_36.setText(_translate("Form", "Phase (deg.)"))
        self.label_43.setText(_translate("Form", "Debug"))
        self.cg635_write_cmd_lineedit.setPlaceholderText(_translate("Form", "*IDN?\\n"))
        self.label_32.setText(_translate("Form", "Basic"))
        self.cg635_set_current_phase_zero_btn.setText(_translate("Form", "Define Current Phase as Zero"))
        self.cg635_freq_units_combobox.setItemText(0, _translate("Form", "Hz"))
        self.cg635_freq_units_combobox.setItemText(1, _translate("Form", "kHz"))
        self.cg635_freq_units_combobox.setItemText(2, _translate("Form", "MHz"))
        self.cg635_freq_units_combobox.setItemText(3, _translate("Form", "GHz"))
        self.cg635_run_btn.setText(_translate("Form", "Run"))
        self.cg635_check_errors_btn.setText(_translate("Form", "Check for Errors"))
        self.label_33.setText(_translate("Form", "Manual Command"))
        self.cg635_stop_btn.setText(_translate("Form", "Stop"))
        self.label_35.setText(_translate("Form", "Frequency"))
        self.label_34.setText(_translate("Form", "Max Frequency (MHz):"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cg635_tab), _translate("Form", "CG635"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cryostat_tab), _translate("Form", "Cryostat/Magnet"))
        self.label_48.setText(_translate("Form", "Bias Power (ch1)"))
        self.toptica_emission_indicator.setText(_translate("Form", "<html><head/><body><p><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/><img src=\":/led_icons/RED_LED_OFF.png\"/></p><p>laser OFF</p></body></html>"))
        self.toptica_temp_stable_indicator.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Temperature Stable (not programmed yet)? </span></p><p align=\"center\"><img src=\":/led_icons/RED_LED_OFF.png\"/></p></body></html>"))
        self.toptica_bias_units_combobox.setItemText(0, _translate("Form", "μW"))
        self.toptica_bias_units_combobox.setItemText(1, _translate("Form", "mW"))
        self.toptica_enable_digital_input_btn.setText(_translate("Form", "￼￼￼￼External Digital Modulation Enable"))
        self.toptica_units_combobox.setItemText(0, _translate("Form", "μW"))
        self.toptica_units_combobox.setItemText(1, _translate("Form", "mW"))
        self.label_47.setText(_translate("Form", "Laser Power (ch2)"))
        self.label_46.setText(_translate("Form", "START:"))
        self.pushButton_3.setText(_translate("Form", "Enable (ch. 1)"))
        self.toptica_start_laser_btn.setText(_translate("Form", "Normal Power (ch. 2)"))
        self.toptica_stop_laser_btn.setText(_translate("Form", "STOP"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.laser_tab), _translate("Form", "Laser"))
import led_icons_rc
